### PR TITLE
prepend NewLine to separate merged files

### PR DESCRIPTION
**Pull request by katlimruiz**
This is to avoid syntax errors
Example: 
jquery final line 
`//# sourceMappingURL=jquery.min.map`

invalidates the first line of bootstrap
`/*! * Bootstrap v3.3.5`

when both are in the same line. That is why we need to separate both with a new line.
This only happens when merging two files. If it's only one, do not add it.
Tests were updated as well.

### CODE REVIEW

**Comment by freeranger** [comment]
I'd like to see a test for this new functionality that confirms that multiple files are joined with a separating newline between them.  You have updated the existing tests so they still work but have not added any new tests

**Comment by katlimruiz** [comment]
I;m not sure why it fails, compressednewline.js exists in the repository, exists in csproj (test), is configured as Copy Always.
Even line 259 in AppVeyor, says:  Copying file from "C:\projects\yuicompressor-net\Code\Yahoo.Yui.Compressor.Tests\Javascript Files\compressednewline.js" to "bin\Debug\Javascript Files\compressednewline.js"

**Comment by freeranger** [comment]
Can you make the test name more descriptive please, describing the intent.
The test name should read like english and describe what should happen.
For example:
* When_The_JavaScriptCompressionType_Is_Not_Specified_The_Input_Files_Are_Compressed
* When_The_CompressionType_Is_None_The_Input_Files_Are_Concatenated_Unchanged
* Accents_Should_Be_Retained_When_Encoded_With_UTF8

Your test name is "Verify_MinifiedNoCompression_NewLine".  What does this mean?  What are you verifying?  
"When_The_CompresisonType_Is_None_Then_....[Something_Should_Happen]"

Also would like to see a test with uncompressed files as well as pre-compressed files and since your change is explicitly adding a newline between files, I think you should actually explictly test that a newline is inserted.

Finally, if it doesn't build then it can't come in - we can't accept a broken pull request!

**Comment by freeranger** [comment]
Closing as the author has not been back in touch

**Pull request closed without merging**
