### PR TITLE
Updated projects to use .Net452

### PR DESCRIPTION
**Pull request by solidcloudio**
Existing version failed as Windows Update removed .net 2.0 Framework.  Updated projects to use .net 4.5.2

### CODE REVIEW

**Comment by PureKrome** [comment]
Tests failing, btw.

**Comment by solidcloudio** [comment]
Tests were failing because of: 

public int LineNumberOfTaskNode
        {
            get { throw new NotImplementedException(); }
        }

        public int ColumnNumberOfTaskNode
        {
            get { throw new NotImplementedException(); }
        }

Not sure why they didn't fail before..  This is just in the Stub.. updated to 
public int LineNumberOfTaskNode
        {
            get { return 0; }
        }

        public int ColumnNumberOfTaskNode
        {
            get { return 0; }
        }

Tests Pass..

**Comment by Taritsyn** [comment]
It would be wise to downgrade .NET Framework version from 4.5.2 to 4.5.1. Key libraries are still targeted on .NET Framework 4.5.1 (e.g., [Microsoft.AspNetCore.Mvc](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc/) and [Microsoft.EntityFrameworkCore](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/)).

**Comment by freeranger** [comment]
I don't think we should accept this PR - nobody else has complained it is not working as is.

**Comment by solidcloudio** [comment]
Whats the point?  why leave  "throw new NotImplementedException(); " In place?

Isn't it obvious the tests will fail?  Are they being run?

image

**Comment by freeranger** [comment]
If all the PR did was fix that issue then that's one thing but it upgrades the .NET Framework version too.
Even if this was something desirable, it should be in a separate PR to one for fixing a bug.

**Comment by solidcloudio** [comment]
touche...

**Comment by PureKrome** [comment]
I'll do this.

https://github.com/PureKrome/YUICompressor.NET/issues/22 created.

**Comment by freeranger** [comment]
BTW, All the tests pass with the current code:
image

Perhaps upgrading to 4.x causes some extra method calls in the stub which is why they failed for @solidcloudio when he upgraded it.

**Pull request closed without merging**
